# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Udder' do

pod 'MFSideMenu'

pod 'SDWebImage', '~>3.7'

pod 'TTTAttributedLabel', '~> 1.10.1'

pod 'AFNetworking', '~> 2.5'

end

target 'UdderTests' do

pod 'MFSideMenu'

pod 'SDWebImage', '~>3.7'

pod 'TTTAttributedLabel', '~> 1.10.1'

pod 'AFNetworking', '~> 2.5'


end

